require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WaitersController do

  # This should return the minimal set of attributes required to create a valid
  # Waiter. As you add validations to Waiter, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "id" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WaitersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all waiters as @waiters" do
      waiter = Waiter.create! valid_attributes
      get :index, {}, valid_session
      assigns(:waiters).should eq([waiter])
    end
  end

  describe "GET show" do
    it "assigns the requested waiter as @waiter" do
      waiter = Waiter.create! valid_attributes
      get :show, {:id => waiter.to_param}, valid_session
      assigns(:waiter).should eq(waiter)
    end
  end

  describe "GET new" do
    it "assigns a new waiter as @waiter" do
      get :new, {}, valid_session
      assigns(:waiter).should be_a_new(Waiter)
    end
  end

  describe "GET edit" do
    it "assigns the requested waiter as @waiter" do
      waiter = Waiter.create! valid_attributes
      get :edit, {:id => waiter.to_param}, valid_session
      assigns(:waiter).should eq(waiter)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Waiter" do
        expect {
          post :create, {:waiter => valid_attributes}, valid_session
        }.to change(Waiter, :count).by(1)
      end

      it "assigns a newly created waiter as @waiter" do
        post :create, {:waiter => valid_attributes}, valid_session
        assigns(:waiter).should be_a(Waiter)
        assigns(:waiter).should be_persisted
      end

      it "redirects to the created waiter" do
        post :create, {:waiter => valid_attributes}, valid_session
        response.should redirect_to(Waiter.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved waiter as @waiter" do
        # Trigger the behavior that occurs when invalid params are submitted
        Waiter.any_instance.stub(:save).and_return(false)
        post :create, {:waiter => { "id" => "invalid value" }}, valid_session
        assigns(:waiter).should be_a_new(Waiter)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Waiter.any_instance.stub(:save).and_return(false)
        post :create, {:waiter => { "id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested waiter" do
        waiter = Waiter.create! valid_attributes
        # Assuming there are no other waiters in the database, this
        # specifies that the Waiter created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Waiter.any_instance.should_receive(:update_attributes).with({ "id" => "MyString" })
        put :update, {:id => waiter.to_param, :waiter => { "id" => "MyString" }}, valid_session
      end

      it "assigns the requested waiter as @waiter" do
        waiter = Waiter.create! valid_attributes
        put :update, {:id => waiter.to_param, :waiter => valid_attributes}, valid_session
        assigns(:waiter).should eq(waiter)
      end

      it "redirects to the waiter" do
        waiter = Waiter.create! valid_attributes
        put :update, {:id => waiter.to_param, :waiter => valid_attributes}, valid_session
        response.should redirect_to(waiter)
      end
    end

    describe "with invalid params" do
      it "assigns the waiter as @waiter" do
        waiter = Waiter.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Waiter.any_instance.stub(:save).and_return(false)
        put :update, {:id => waiter.to_param, :waiter => { "id" => "invalid value" }}, valid_session
        assigns(:waiter).should eq(waiter)
      end

      it "re-renders the 'edit' template" do
        waiter = Waiter.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Waiter.any_instance.stub(:save).and_return(false)
        put :update, {:id => waiter.to_param, :waiter => { "id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested waiter" do
      waiter = Waiter.create! valid_attributes
      expect {
        delete :destroy, {:id => waiter.to_param}, valid_session
      }.to change(Waiter, :count).by(-1)
    end

    it "redirects to the waiters list" do
      waiter = Waiter.create! valid_attributes
      delete :destroy, {:id => waiter.to_param}, valid_session
      response.should redirect_to(waiters_url)
    end
  end

end
